dist: focal
sudo: required
language: cpp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-9
      - g++-9
      - libxrandr-dev
      - libxinerama-dev
      - libxcursor-dev
      - libxi-dev
      - libgl1-mesa-dev
#before_install:
#  - sudo apt-get install libsfml-dev
script:
  - gcc -v
  - export CC=gcc-9
  - export CXX=g++-9
  - cmake --target unittests .
  - make -j 4
  - ./build/unittests